on:
  workflow_call:
    inputs:
      FIREBASE_PROJECT_ID:
        description: 'Firebase Project to deploy to'
        required: true
        type: string
    secrets: 
      GH_READ_PACKAGES_TOKEN:
        required: true
      FIREBASE_SERVICE_ACCOUNT_KEY:
        required: true

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@bx-looop'
      
      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_READ_PACKAGES_TOKEN }}
      
      - name: Prepare Firebase
        run: npm run prepare-firebase
      
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
          channelId: live
          projectId: ${{ inputs.FIREBASE_PROJECT_ID }}